//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnTourMetro.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public int Cod_Usuario { get; set; }
        public string Nombres { get; set; }
        public string Colegio { get; set; }
        public string Curso { get; set; }
        public string Appaterno { get; set; }
        public string Apmaterno { get; set; }
        public string Rut { get; set; }
        public string Email { get; set; }
    }
}
